### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by Anonymous-Floof** [ojaha065/PiShockForMC#1]
Could you please add an update for 1.19.3? 

I have a terrifying custom modpack based around being scary and hard, I'd REALLY love to be able to use this with it!

**Comment by ojaha065** [comment]
Hi @Garridan,

just pushed a new release. Tested and works on MC 1.19.3 with Forge 44.1.0 but any Forge version >=44 should be fine.

As a side note, I find it baffling that nowadays Forge seems to get a new major release for every Minecraft patch. Like Minecraft 1.19.3 has Forge 44.x but 1.19.4 has 45.x. Makes it unnecessarily hard to have mods support multiple MC versions.
