### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by TueffyT** [ojaha065/PiShockForMC#2]
Would it be possible to get a 1.20.1 build? 
From my quick glance at the code I had it should just need a build against the new Forge version right? 
Might try to do it myself later, but would rather have the original author do it. Been ages I did anything Java.

**Comment by ojaha065** [comment]
My experience with Forge is still pretty limited but as far I understand it, updating [the versionRange value in mods.toml](https://github.com/ojaha065/PiShockForMC/blob/main/src/main/resources/META-INF/mods.toml#L41) to [include](https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html) 1.20 should be enough and the thing should be compatible with both 1.19.x and 1.20.x.

That is, as long as there isn't any breaking changes in 1.20.x Forge. I haven't checked the changelog, but I think it's pretty unlikely that there are any that would affect this mod.

I will test this sometime soon when I have the time. Or feel free to test it yourself and send a PR.

**Comment by ojaha065** [comment]
The latest release now supports MC 1.20.x
